var ewaybillNo=null;
var ewayBillid=null;
var ewaybillStatus=null;
var docDate = null;

function sendMail(idValue){
	$(".loader").show(); 
	  $.ajax({
			url : "sendMailToCustomerFromPreview",
			method : "post",
			contentType : "application/json",
			dataType : "json",
			data : { "id" : idValue },
			headers: {_csrf_token : $("#_csrf_token").val()},
			async : false,
			success:function(json,fTextStatus,fRequest){
				if (isValidSession(json) == 'No') {
					window.location.href = getDefaultSessionExpirePage();
					return;
				}

				if(isValidToken(json) == 'No'){
					window.location.href = getCsrfErrorPage();
					return;
				}
				//var json = $.parseJSON(jsonobj);
				bootbox.alert(json);
				setCsrfToken(fRequest.getResponseHeader('_csrf_token'));
			},
			error: function (data,status,er) {
				 
				 getInternalServerErrorPage();   
			}
		});
	  $(".loader").fadeOut("slow"); 
}


function download(idValue){
	$(".loader").show(); 
	  $.ajax({
			url : "sendMailToCustomerFromPreview",
			method : "post",
			contentType : "application/json",
			dataType : "json",
			data : { "id" : idValue },
			headers: {_csrf_token : $("#_csrf_token").val()},
			async : false,
			success:function(json,fTextStatus,fRequest){
				if (isValidSession(json) == 'No') {
					window.location.href = getDefaultSessionExpirePage();
					return;
				}

				if(isValidToken(json) == 'No'){
					window.location.href = getCsrfErrorPage();
					return;
				}
				//var json = $.parseJSON(jsonobj);
				bootbox.alert(json);
				setCsrfToken(fRequest.getResponseHeader('_csrf_token'));
			},
			error: function (data,status,er) {
				 
				 getInternalServerErrorPage();   
			}
		});
	  $(".loader").fadeOut("slow"); 
}



function backToInvoicePage(idValue){
	$('.loader').show();
	document.manageInvoice.action = "./getInvoiceDetails";
	document.manageInvoice.id.value = idValue;
	document.manageInvoice._csrf_token.value = $("#_csrf_token").val();
	document.manageInvoice.submit();
	$(".loader").fadeOut("slow");
}


function getEWayBillDetails(idValue){
	$('.loader').show();
	$('#card').hide();
	$("#firstDivId").hide();
	$("#breadcumheader").hide();
	setValuesInHiddenFields(idValue);
	setTimeout(function(){
		getEwayBillDetailsInPreview(idValue);
		$("#secondDivId").show();
		$("#headerPreview").show();
		$("#previewButtons").show();
		$('#card').show();
		$(".loader").fadeOut("slow"); 
	}, 2000);
	
}


function setValuesInHiddenFields(idValue){
	$("#refInvoiceId").val(idValue);
}

function getEwayBillDetailsInPreview(idValue){
	var location = $("#location").val();
	var backendResponse = '';
	 $.ajax({
			url : "getEwayBillDetailsInPreview",
			method : "post",
			data : {id : idValue},
		//	contentType : "application/json",
			dataType : "json",
			headers: {_csrf_token : $("#_csrf_token").val()},
			async : false,
			success:function(data,fTextStatus,fRequest){
				if (isValidSession(data) == 'No') {
					window.location.href = getDefaultSessionExpirePage();
					return;
				}

				if(isValidToken(data) == 'No'){
					window.location.href = getCsrfErrorPage();
					return;
				}
				
				console.log(data);
				if(data.renderData === 'accessDeny'){
					 $(".loader").fadeOut("slow"); 
					bootbox.alert("Data is manipulated.", function() {
						window.location.href =  'home#invoice';
					});
				}else{
					ewaybillNo=data.ewaybillNo;
					ewayBillid=data.id;
					ewaybillStatus=data.ewaybillStatus;
					docDate = new Date(data.docDate);
					var day = docDate.getDate();
					var month = docDate.getMonth()+1;
					var year = docDate.getFullYear();
					var documentDate = day+"/"+month+"/"+year;
				//	 $("#etable").html("");
												 
							 $("#etable").append(
									 '<div class="col-md-6">'
										    +'<strong>eWay Bill No : </strong>'+data.ewaybillNo +'<br>'
											+'<strong>Generated By : </strong>'+data.gstin+'<br>'
											+'<strong>Mode : </strong>'+data.modeOfTransportDesc+'<br>'
											+'<strong>Type : </strong>'+data.supplyType+'-'+data.subSupplyType+''
									+'</div>'
									+'<div class="col-sm-6">'
											+'<strong>Generated Date : </strong>'+data.ewaybill_date+'<br>'
											+'<strong>Valid Upto : </strong>'+data.ewaybill_valid_upto+'<br>'
											+'<strong>Approx Distance : </strong>'+data.kmsToBeTravelled+'<br>'
											+'<strong>Document Details : </strong>'+data.docType+' - '+data.docNo +' - '+documentDate+''
									+'</div>'
							 );	
							 
							 var label1 = "Transporter Doc. No: ";
							 var label2 = "Transporter Doc Date: ";	
							 
							 if(data.modeOfTransportDesc == 'Road'){
								 label1 = "Transporter Doc. No: ";
								 label2 = "Transporter Doc Date: ";
							 } else if(data.modeOfTransportDesc == 'Rail'){
								 label1 = "RR No: ";
								 label2 = "RR Date: ";
							 }else if(data.modeOfTransportDesc == 'Air'){
								 label1 = "Airway Bill No: ";
								 label2 = "Airway Bill Date: ";
							 }else if(data.modeOfTransportDesc == 'Ship'){
								 label1 = "Bill of lading No: ";
								 label2 = "Bill of lading Date: ";
							 } 
													
							 
							 $("#transportTable").append('<div class="col-md-3"><strong>'+label1+'</strong>'+data.docNo+'</div>'
			                        + '<div class="col-md-3"><strong>'+label2+'</strong> '+documentDate+'</div>'
			                        + '<div class="col-md-3"><strong> Transporter ID : </strong>'+data.transporterId+'</div>'
			                        + '<div class="col-md-3"><strong> Transporter Name : </strong>'+data.transporterName+'</div>'
							 );						
								
								if(data.modeOfTransportDesc == 'Road'){
										
										 $("#vehicleDetTable tbody:last-child").append(
									 				'<tr>'	
									 					 +'<td>'+data.modeOfTransportDesc+'</td>'
									                     +'<td>'+data.vehicleNo +'</td>'
									                     +'<td>'+location+'</td>'
									                     +'<td>'+data.ewaybill_date+'</td>'
									                     +'<td>'+data.gstin+'</td>'
									                     +'<td>-</td>'
									 				+'</tr>'	
											 	);
									 } else {
										 $("#vehicleDetTable tbody:last-child").append(
									 				'<tr>'	
									 					 +'<td>'+data.modeOfTransportDesc+'</td>'
									                     +'<td>-</td>'
									                     +'<td>'+location+'</td>'
									                     +'<td>'+data.ewaybill_date+'</td>'
									                     +'<td>'+data.gstin+'</td>'
									                     +'<td>-</td>'
									 				+'</tr>'	
											 	);
									 }
							 
									 
				}
				setCsrfToken(fRequest.getResponseHeader('_csrf_token'));
	         },
	         error: function (data,status,er) {
	        	 
	        	 getInternalServerErrorPage();   
	        }
		});
	 $(".loader").fadeOut("slow"); 
	 return backendResponse;
}


function redirectToInvoiceHistoryPage(){
	return 'getMyInvoices';
}

function generateEWayBill(idValue){
	$('.loader').show();
	document.manageInvoice.action = "./generateEWayBill";
	document.manageInvoice.id.value = idValue;
	document.manageInvoice._csrf_token.value = $("#_csrf_token").val();
	document.manageInvoice.submit();
	$(".loader").fadeOut("slow");
}


function getEWayBills(idValue){
	$('.loader').show();
	document.manageInvoice.action = "./getEWayBills";
	document.manageInvoice.id.value = idValue;
	document.manageInvoice._csrf_token.value = $("#_csrf_token").val();
	document.manageInvoice.submit();
	$(".loader").fadeOut("slow");
}



function downloadEWayBills(gstin, invoiceId ){
	$('.loader').show();
	document.downloadEWayBill.action = "./downloadEWayBill";
	document.downloadEWayBill.invoiceId.value = invoiceId;
	document.downloadEWayBill.gstin.value = gstin;
	document.downloadEWayBill.ewaybillNo.value = ewaybillNo;
	document.downloadEWayBill._csrf_token.value = $("#_csrf_token").val();
	document.downloadEWayBill.submit();
	$(".loader").fadeOut("slow");
}


function sendEwayBillPdf(gstin, invoiceId) {
	$('.loader').show();
	$('#mainPg1').hide();
	var inputData = {
		"invoiceId" : invoiceId,
		"gstin" : gstin,
		"ewaybillNo" : ewaybillNo,
	};

	var data = JSON.stringify(inputData);
	$.ajax({
		url : "sendEwayBillPdf",
		method : "post",
		data : data,
		contentType : "application/json",
		dataType : "json",
		headers: {_csrf_token : $("#_csrf_token").val()},
		async : false,
		success : function(json,fTextStatus,fRequest) {
			
			if (isValidSession(json) == 'No') {
				window.location.href = getDefaultSessionExpirePage();
				return;
			}

			if(isValidToken(json) == 'No'){
				window.location.href = getCsrfErrorPage();
				return;
			}
			
			if (json.status == 'success') {
				 $(".loader").fadeOut("slow"); 
				bootbox.alert("E-way Bill PDF sent successfully", function() {
					getEWayBills(invoiceId);
				});
			}

			if (json.status == 'failure') {
				 $(".loader").fadeOut("slow"); 
				bootbox.alert("Error while sending E-way Bill Pdf ");

			}
			setCsrfToken(fRequest.getResponseHeader('_csrf_token'));
			
		},
		error : function(data, status, er) {
			// alert("error: "+data+" status: "+status+" er:"+er);
			 getInternalServerErrorPage();   
		}
	});
	$(".loader").fadeOut("slow"); 
}

function canceleWayBillPage(invoiceId){
	if(ewaybillStatus == 'GENEWAYBILL'){
	$('.loader').show();
	document.cancelEwayBill.action = "./cancelEWayBillPage";
	document.cancelEwayBill.id.value = invoiceId;
	document.cancelEwayBill.ewayBillId.value = ewayBillid;
	document.cancelEwayBill._csrf_token.value = $("#_csrf_token").val();
	document.cancelEwayBill.submit();
	$(".loader").fadeOut("slow");
	} else {
		bootbox.alert("This E-Way Bill is cancelled already");
	} 
}

$(document).ready(function () {
	if($('#isInvoiceAllowed').val() == 'true'){
		loadEWaybillTable();
	}
	//createDataTable('throughInvEwayBillTab');
	$('#throughInvEwayBillTab').DataTable({
    	bSort: false,
        rowReorder: {
              selector: 'td:nth-child(2)'
        },
        responsive: true
});
	$(".loader").fadeOut("slow"); 
	$("#backToPreview").click(function(e){
		$('.loader').show();
		
		$("#secondDivId").hide();
		$("#headerPreview").hide();
		$("#previewButtons").hide();
		setValuesInHiddenFields("");
		setTimeout(function(){
			$("#firstDivId").show();
			$("#breadcumheader").show();
			 $(".loader").fadeOut("slow"); 
		}, 500);
	});
	
	$("#optionsDiv").click(function(e){
		$('#optionsMultiDiv').show();
		$('#optionsDiv').hide();
		
	});
});


function loadEWaybillTable(){
	var invid = $('#numberinvoice').val();
	$.ajax({
		url : "getEwayBillListAndCutomer",
		method : "post",
		data : {id : invid},
		/*contentType : "application/json",*/
		dataType : "json",
		headers: {_csrf_token : $("#_csrf_token").val()},
		async : false,
		success : function(json,fTextStatus,fRequest) {
			
			if (isValidSession(json) == 'No') {
				window.location.href = getDefaultSessionExpirePage();
				return;
			}

			if(isValidToken(json) == 'No'){
				window.location.href = getCsrfErrorPage();
				return;
			}
			setCsrfToken(fRequest.getResponseHeader('_csrf_token'));
			
		/*	if(json.status == 'failure'){
				//bootbox.alert(response.error_desc);
			}else{*/
				$.each(json, function (a, b) {
					var stat;
					if(b[5]=='GENEWAYBILL'){
						stat = '<span class="textColourGreen">Valid</span>';
					}else if(b[5]=='CANEWB'){
						stat = '<span class="textColourRed">Cancelled</span>';
					}else{
						stat = '<span class="textColourRed">Invalid</span>';
					}
					
					 $('#throughInvEwayBillTab tbody:last-child').append(
						'<tr>'
							 /*+'<td>'+(a+1)+'</td>'*/
	                		 +'<td><a href="#" onclick="javascript:getEWayBillDetails('+b[7]+','+b[0]+');">'+b[0]+'</a></td>'
	                		 +'<td>'+b[3]+'</td>'
	                		 +'<td>'+b[1]+'</td>'
	                		 +'<td>'+b[4]+'</td>'
	                		 +'<td>'+stat+'</td>'
	                		 +'<td>'+b[6]+'</td>'
	                    +'</tr>');
	            });
			//} 
			
		},
		error : function(data, status, er) {
			 getInternalServerErrorPage();   
		}
	});
}