var ewaybillNo=null;
var ewayBillid=null;
var ewaybillStatus=null;
var docDate = null;
var gstin = "";
var clientId = $("#clientId").val(); 
var secretKey = $("#secretKey").val(); 
var userId = $("#userId").val();
var appCode = $("#appCode").val();
var ipUsr = $("#ipUsr").val();
var ewaybillNo = $("#ewaybillNo").val();


$(document).ready(function(){

	var jsonData = {"userId" : userId, "ewaybillno" : ewaybillNo};
	$.ajax({
	 	url : "ewaybill/getEwayBillByNumber",
	 	type : "POST",
	 	contentType : "application/json",
		dataType : "json",
		headers: {client_id : clientId, secret_key : secretKey, app_code : appCode, ip_usr : ipUsr},
		data : JSON.stringify(jsonData),
		async : false,
		success:function(data,fTextStatus,fRequest){
			if (isValidSession(data) == 'No') {
				window.location.href = getDefaultSessionExpirePage();
				return;
			}
			
			if(data.status === 'failure'){
				bootbox.alert(error_desc, function() {
					setTimeout(function(){
						backToDocumets();
					}, 500);
				});
			}else{
			//	ewaybillNo=data.ewaybillNo;
				ewayBillid=data.id;
				ewaybillStatus=data.ewaybillStatus;
				var totalAmount = 0;
				var cessTotalTax = 0;
				var sgstAmount = 0;
				var cgstAmount = 0;
				var igstAmount = 0;
				var otherValue = 0;
				var cessadvolAmount = 0;
				var cessnonadvolAmount = 0;
				var othSubType = "";
				if(data.subSupplyDesc == 'Others'){
					othSubType = "-("+data.othersSubType+")";
				}
				 
				if(data.supplyType == 'O'){
					 gstin = data.fromGstin;
				 } else {
					 gstin = data.toGstin;
				 }
				
				 $("#etable").append(
					 '<div class="col-sm-6">'
						+'<div class="invoiceInfo ">'
						    +'<b>eWay Bill No : </b>'+data.ewayBillNo +'<br>'
							+'<b>Generated By : </b>'+gstin+'<br>'
							+'<b>Mode : </b>'+data.transModeDesc+'<br>'
							+'<b>Type : </b>'+data.supplyTypeDesc+'-'+data.subSupplyDesc+othSubType+'<br>'
						+'</div>'
					+'</div>'
					+'<div class="col-sm-6">'
						+'<div class="invoiceInfo ">'
							+'<b>Generated Date : </b>'+data.ewayBillDate+'<br>'
							+'<b>Valid Upto : </b>'+data.ewaybill_valid_upto+'<br>'
							+'<b>Approx Distance : </b>'+data.transDistance+'<br>'
							+'<b>Document Details : </b>'+data.docTypeDesc+' - '+data.docNo +' - '+data.docDate+'<br>'
						+'</div>'
					+'</div>'
				 );		
				 
				 $("#fromGstin").append(
					'<strong>From</strong><br>'	
					+ '<b>GSTIN :</b>'+data.fromGstin+'<br>'
					+  data.fromTrdName+'<br>'
					+ '<b>Address :</b>'+data.fromAddr1+'<br>'
					+ data.fromPlace+'<br>'
					+ data.fromPincode+'<br>'					 
				 );
				 
				 $("#toGstin").append(
					 '<strong>To</strong><br>'
					+'<b>GSTIN :</b>'+data.toGstin+'<br>'
					+  data.toTrdName+'<br>'
					+'<b>Address :</b>'+data.toAddr1+'<br>'
					+ data.toPlace+'<br>'
					+ data.toPincode+'<br>'						 
				 );				 

				 $.each(data.itemList,function(i,value){
					var taxAmt = (value.cgstRate+value.sgstRate+value.igstRate+value.cessadvolAmount+value.cessnonadvolAmount);
					$("#mytable2 tbody:last-child").append(
						'<tr>'		                        
						+ '<td>'+value.hsnCode+'</td>'
						+ '<td>'+value.productName+'</td>'
						+ '<td>'+value.quantity+'</td>'
						+ '<td>'+value.taxableAmount+'</td>'
						+ '<td>'+taxAmt+'</td>'
				    	+ '</tr>'
				 	);
					 totalAmount = totalAmount + value.taxableAmount;								 
				 });

				 cessadvolAmount = cessadvolAmount + data.cessadvolAmount;
				 cessnonadvolAmount= cessnonadvolAmount + data.cessnonadvolAmount;
				 sgstAmount = sgstAmount + data.sgstValue;
				 cgstAmount = cgstAmount + data.cgstValue;
				 igstAmount = igstAmount + data.igstValue;
				 otherValue = otherValue + data.otherValue;
				 
				 
				 $("#itemTaxDet").append(
					  ' <b>Total Taxable Amt : </b>'+data.totalValue//+'<br>' 
					 +'&nbsp;&nbsp;&nbsp;&nbsp;<b> CGST Amt : </b>'+cgstAmount//+'<br>'
					 +'&nbsp;&nbsp;&nbsp;&nbsp;<b> SGST Amt : </b>'+sgstAmount//+'<br>'
	                 +'&nbsp;&nbsp;&nbsp;&nbsp;<b> IGST Amt : </b>'+igstAmount//+'<br>'
	                 +'&nbsp;&nbsp;&nbsp;&nbsp;<b> CESS Advol Amt : </b>'+cessadvolAmount
	                 +'&nbsp;&nbsp;&nbsp;&nbsp;<b>CESS Non. Advol Amt : </b>'+cessnonadvolAmount//+'<br>'
	                 +'&nbsp;&nbsp;&nbsp;&nbsp;<b>Other Amt : </b>'+otherValue//+'<br>'
	                 +'&nbsp;&nbsp;&nbsp;&nbsp;<b>Total Inv. Amt : </b>'+data.totInvValue//+'<br>'
				 );
					
				 var label1 = "Transporter Doc. No: ";
				 var label2 = "Transporter Doc Date: ";	
				 
				 if(data.transModeDesc == 'Road'){
					 label1 = "Transporter Doc. No: ";
					 label2 = "Transporter Doc Date: ";
				 } else if(data.transModeDesc == 'Rail'){
					 label1 = "RR No: ";
					 label2 = "RR Date: ";
				 }else if(data.transModeDesc == 'Air'){
					 label1 = "Airway Bill No: ";
					 label2 = "Airway Bill Date: ";
				 }else if(data.transModeDesc == 'Ship'){
					 label1 = "Bill of lading No: ";
					 label2 = "Bill of lading Date: ";
				 } 
				 
				 $("#transportTable").append(						
                          '<b>'+label1+'</b>'+data.transDocNo//+'<br>'
                        + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>'+label2+'</b> '+data.transDocDate//+'<br>'
                        + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b> Transporter ID : </b>'+data.transporterId//+'<br>'
                        + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b> Transporter Name : </b>'+data.transporterName//+'<br>'
				 );						
						
				 if(data.transModeDesc == 'Road'){
				 	$("#vehicleDetTable tbody:last-child").append(
				 					 '<tr>'	
				 					 +'<td>'+data.transModeDesc+'</td>'
				                     +'<td>'+data.vehicleNo +'</td>'
				                     +'<td>'+data.fromPlace+'</td>'
				                     +'<td>'+data.ewayBillDate +'</td>'
				                     +'<td>'+gstin+'</td>'
				                     +'<td>-</td>'
				 					 +'</tr>'	
				 	);
				 }else{
				 	$("#vehicleDetTable tbody:last-child").append(
				 					 '<tr>'	
				 					 +'<td>'+data.transModeDesc+'</td>'
				                     +'<td>-</td>'
				                     +'<td>'+data.fromPlace+'</td>'
				                     +'<td>'+data.ewayBillDate +'</td>'
				                     +'<td>'+gstin+'</td>'
				                     +'<td>-</td>'
				 					 +'</tr>'	
				 	);
				 }
			}
         },
         error: function (data,status,er) {        	 
        	 getWizardInternalServerErrorPage();   
        }

	});
});


function backToDocumets(){	
	window.location.href = "./wizardGetGenericEWayBills";
}

function downloadWIEWayBills(userId, ewaybillno, client_id, secret_key, app_code, ip_usr){
	document.downloadWIEWayBill.action = "./ewaybill/generatedEWayBillDownload";
	document.downloadWIEWayBill.userId.value = userId;
	document.downloadWIEWayBill.ewaybillno.value = ewaybillno;
	document.downloadWIEWayBill.client_id.value = client_id;
	document.downloadWIEWayBill.secret_key.value = secret_key;
	document.downloadWIEWayBill.app_code.value = app_code;
	document.downloadWIEWayBill.ip_usr.value = ip_usr;
	document.downloadWIEWayBill.submit();
}

function canceleWayBillPage(){
	if(ewaybillStatus == 'GENEWAYBILL'){
	document.cancelEwayBill.action = "./cancelWizardGenEWayBillPage";
	document.cancelEwayBill.ewayBillNo.value = ewaybillNo;
	document.cancelEwayBill.gstin.value = gstin;
	document.cancelEwayBill.submit();
	} else {
		bootbox.alert("This E-Way Bill is cancelled already");
	} 
}
