<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../../layout/taglib.jsp" %> 



    <!-- Dashboard set variables - Start -->
<input type="hidden" id="dash_conditionValue" name="dash_conditionValue" value="${dash_conditionValue}">
<input type="hidden" id="dash_startdate" name="dash_startdate" value="${dash_startdate}">
<input type="hidden" id="dash_enddate" name="dash_enddate" value="${dash_enddate}">
<input type="hidden" id="onlyMonth" name="onlyMonth" value="${onlyMonth}">
<input type="hidden" id="onlyYear" name="onlyYear" value="${onlyYear}">



    <header class="insidehead">
    <a id="goBackToInvoiceEwaybill" href="#" class="btn-back"><i class="fa fa-angle-left"></i></a>
   
     <a class="logoText" href="./home">
      	<a class="logoText" href="home#invoice"><img src="<spring:url value="/resources/images/home/gst_logo.jpg" />" class="img-responsive"> <span1> Bill Lite </span1></a>	
      </a>
</header>
<html>

<body>
<main>
	<section class="block ">
	<input type="hidden" id="_csrf_token" name="_csrf_token" value="${_csrf_token}" />
		<div class="container" id='loadingmessage' style='display:none;' align="middle">
		  <img src='<spring:url value="/resources/images/loading.gif"/>'/>
		</div>
		<div class="container">
			<div class="card">

				<div class="invoicePage"> <!-- id="secondDivId" style="display:none"> -->
				<span>
					
				<div class="row">
					<div class="invoiceDetail">
							
								<div id="etable">
								 <h5> 1. E-Way Bill Details </h5> <br>
								 <div class="col-sm-6">
								<div class="invoiceInfo ">
							    <p> <span>eWay Bill No: </span>${invoiceEWayBill[0].ewaybillNo}</p>
								<p> <span>Generated By: </span>${invoiceEWayBill[0].gstin}</p>
								<p> <span>Mode: </span>${invoiceEWayBill[0].modeOfTransportDesc}</p>
								<p> <span>Type: </span>${invoiceEWayBill[0].supplyType}-${invoiceEWayBill[0].subSupplyType}</p>
								</div>
								</div>
								<div class="col-sm-6">
						        <div class="invoiceInfo ">
								<p> <span>Generated Date: </span>${invoiceEWayBill[0].ewaybill_date}</p>
								<p> <span>Valid Upto: </span>${invoiceEWayBill[0].ewaybill_valid_upto}</p>
								<p> <span>Approx Distance: </span>${invoiceEWayBill[0].kmsToBeTravelled}</p>
								<p> <span>Document Details: </span>${invoiceEWayBill[0].docType}-${invoiceEWayBill[0].docNo}-<fmt:formatDate pattern="dd/MM/yyyy" value="${invoiceEWayBill[0].docDate}" /></p>
								</div>
								</div>
								</div>
					</div>
				</div>
						<div class="row">
						<div class="invoiceDetail">
						<h5> 2. Address Details </h5>  <br>
						<div class="col-sm-6">
							<div class="invoiceInfo ">
							 
							<h6>From</h6>
							<p><span>GSTIN:</span>${gstinDetails.gstinNo }</p>
							<p><span>Address:</span>${gstinDetails.gstinAddressMapping.address }</p>
							<p><span></span>${gstinDetails.gstinAddressMapping.city }</p>
							<p><span></span>${gstinDetails.gstinAddressMapping.state } </p>
							<p><span></span>${gstinDetails.gstinAddressMapping.pinCode }</p>
							
							</div>
						</div>
						<c:if test="${invoiceDetails.invoiceFor  == 'Product'}">
							<c:if test="${invoiceDetails.billToShipIsChecked == 'No' }">
								<div class="col-sm-6">
									<div class="invoiceInfo ">
									<h6>To</h6>
									<c:if test="${not empty invoiceDetails.customerDetails.custGstinState != 'NULL'}">
									<p><span>GSTIN:</span>${EwayBillWITransaction[0].toGstin }</p>
									</c:if>
									<p><span>Address:</span>${EwayBillWITransaction[0].toAddress1 }</p>
									<p><span></span>${EwayBillWITransaction[0].toPlace}</p>
									<p><span>Pincode:</span>${EwayBillWITransaction[0].toPincode }</p>
									</div>
								</div>
							</c:if>
							<c:if test="${invoiceDetails.billToShipIsChecked == 'Yes' }">
								<div class="col-sm-6">
									<div class="invoiceInfo">
									<h6>To</h6>
									<c:if test="${not empty invoiceDetails.customerDetails.custGstinState != 'NULL'}">
										<p><span>GSTIN:</span>${invoiceDetails.customerDetails.custGstId }</p>
										</c:if>
										<p><span>Address:</span>${invoiceDetails.customerDetails.custAddress1 }</p>
										<p><span></span>${invoiceDetails.customerDetails.custCity }</p>
										<p><span></span>${invoiceDetails.customerDetails.custState } </p>
										<p><span></span>${invoiceDetails.customerDetails.pinCode }</p>
										
									</div>
								</div>
							</c:if>
						</c:if>
						</div>
					</div>
						
					<!-- Start -->
					<div class="row">
				<!-- 	<div class="invoiceTable"> -->
			          	 
			          	 <div class="invoiceDetail">
								<!-- <div id="invoiceTable"> -->
								<h5> 3. Goods Details </h5>  <br>
								<div class="invoiceTable">
						
                          <!-- First Table Starts -->
                          <div id="">
                          
                          	<ul class="e-productdet headers">
                               <li>HSN Code</li>
                               <li>Product Descripition</li>
                               <li>Quantity</li>
                               <li>Taxable Amount Rs.</li>
                               <li>Tax Rate</li>
                            </ul>
                            <c:forEach items="${ewayBillWIItem}" var="ewayBillWIItem">
                            <ul class="e-productdet">
                            
                               <li>${ewayBillWIItem[0].hsnCode }</li>
                               <li>${ewayBillWIItem[0].productName }</li>
                               <li>${ewayBillWIItem[0].quantity }</li>
                               <li><fmt:formatNumber type = "number" value = "${ewayBillWIItem[0].taxableAmount}" /></li>
                               <li>${ewayBillWIItem[0].cgstRate+ ewayBillWIItem[0].sgstRate+ ewayBillWIItem[0].igstRate }</li>
                               
                              
                            </ul>
                            </c:forEach>
                            
                            <c:set var="totalAmount" value="${0}"/>
							<c:set var="cessTotalTax" value="${0}"/>
							<c:set var="categoryType" value=""/>
                            	 
                            	   <c:forEach items="${invoiceDetails.serviceList }" var = "data">
										<c:set var="totalTaxRate" value="${data.sgstPercentage + data.cgstPercentage + data.igstPercentage}" />
										<ul class="e-productdet" id="invoiceDet">
											<li>${data.hsnSacCode }</li>
		                                  	<li>${data.serviceIdInString }</li>
		                                   	<li>${data.quantity }</li>
		                                   	<li class="text-right"><fmt:formatNumber minFractionDigits="2" type="number" maxFractionDigits="2" value="${data.previousAmount - data.offerAmount + data.additionalAmount}"/></li>
		                                   	<li class="text-right"><fmt:formatNumber minFractionDigits="2" type="number" maxFractionDigits="2" value="${totalTaxRate }"/></li>
		                                   	                                   
		                                </ul>
		                                
		                                <c:set var="cessTotalTax" value="${cessTotalTax + data.cess}" />
										<c:set var="totalAmount" value="${totalAmount + (data.previousAmount - data.offerAmount + data.additionalAmount )}" />
										<c:set var="sgstAmount" value="${sgstAmount + data.sgstAmount}" />
										<c:set var="cgstAmount" value="${cgstAmount + data.cgstAmount}" />
										<c:set var="igstAmount" value="${igstAmount + data.igstAmount}" />
										
									</c:forEach>
                            	<br>
                            	 </div>
                            </div>
                            <!-- </div>
                            </div>
                            	<div class="invoiceDetail">  -->
                           	 <div class="col-sm-6">
							<div class="invoiceInfo ">
                            <p><span>Total Tax'ble Amount : </span> <fmt:formatNumber type = "number" value = "${totalAmount }" /><br/> 
                            <span> CGST Amount : </span>  <fmt:formatNumber type = "number" value = "${cgstAmount }" /><br/> 
                            <span> SGST Amount : </span> <fmt:formatNumber type = "number" value = "${sgstAmount }" /><br/> 
                            <span> IGST Amount : </span><fmt:formatNumber type = "number" value = "${igstAmount } " /><br/>
                             <span> CESS Amount : </span> <fmt:formatNumber type = "number" value = "${cessTotalTax }" /></p>
                            </div>
                            </div> 
                             </div>	
						
			         <!--  	</div> -->
			          	 </div>
					 
					  <div class="row">
							<div class="invoiceDetail">
							 <h5> 4. Transportation Details </h5> <br>
							<div class="col-sm-6">
							<div class="invoiceInfo " >
							
							<c:if test="${invoiceEWayBill[0].modeOfTransportDesc  == 'Rail'}">
						<c:set var="conditionValue" value="RR"/>
						</c:if>
						<c:if test="${invoiceEWayBill[0].modeOfTransportDesc == 'Road'}">
						<c:set var="conditionValue" value="Transporter Doc"/>
						</c:if>
						<c:if test="${invoiceEWayBill[0].modeOfTransportDesc  == 'Air'}">
						<c:set var="conditionValue" value="Airway Bill"/>
						</c:if>
						<c:if test="${invoiceEWayBill[0].modeOfTransportDesc  == 'Ship'}">
						<c:set var="conditionValue" value="Bill of lading"/>
						</c:if>
							
							 <p><span>${conditionValue} No: </span>${invoiceEWayBill[0].docNo}<br/> 
							 <span> ${conditionValue} Date : </span><fmt:formatDate pattern="dd/MM/yyyy" value="${invoiceEWayBill[0].docDate}" /> <br/> 
							 <span> Transporter ID: </span> ${invoiceEWayBill[0].transporterId}<br/>
                             <span> Transporter Name : </span>${invoiceEWayBill[0].transporterName} <br/> </p>
								
								 </div>
								 </div>
								
							</div>
						</div>
						 <div class="row">
						<!-- 	<div class="invoiceTable">	 -->				
						<div id="vehicleTable">
								
								<h5> 5. Vehicle Details </h5>
								<div class="invoiceTable">
						
                          <!-- First Table Starts -->
                          <div id="">
                          <input type="hidden" name="location" id="location" value="${gstinDetails.gstinAddressMapping.state }">
                          
                          	<ul class="transportdet headers">
                               <li>Mode</li>
                               <li>Vehicle / Trans <br> Doc No & Dt.</li>
                               <li>From</li>
                               <li>Entered Date</li>
                               <li>Entered By</li>	
                               <li>CEWB No.<br> (If any)</li>
                            </ul>
                            	 <ul class="transportdet" id="vehicleDet">
                            	 <li>${invoiceEWayBill[0].modeOfTransportDesc}</li>
                               <li>${invoiceEWayBill[0].vehicleNo}</li>
                               <li>${gstinDetails.gstinAddressMapping.state } </li>
                               <li>${invoiceEWayBill[0].ewaybill_date}</li>
                               <li>${ewaybillList[0].gstin}</li>
                               <li></li>
                            	 </ul>
                            </div>
                            </div>
						</div>
					<!-- 	</div> --> 	
						</div>
					<!-- End -->	
					
					<br>
					
					 <%-- <div class="row text-center" id="optionsMultiDiv">
        			 <div class="btns"> 
				        
        				 <a href="#" onclick="javascript:sendEwayBillPdf('${invoiceDetails.gstnStateIdInString }', '${invoiceDetails.id }');" class="btn btn-info" style="margin:5px 0 0 0">
          					<span class="glyphicon glyphicon-envelope"></span> Send eWay Bill
        				</a>
        				
        				 
        				<a href="#" onclick="javascript:canceleWayBillPage('${invoiceDetails.id}');" class="btn btn-info" style="margin:5px 0 0 0">
	          					<span class="glyphicon glyphicon-remove"></span> Cancel
	        				</a>
	        			
        				<br/>
        				
				    </div>
				    </div> --%>
				</section>
				</main>
				
<script type="text/javascript" src="<spring:url value="/resources/js/DashBoard/dashboardInvoiceEwaybill.js" />"></script>

</body>
</html>
<!-- Dashboard backToCall form -->
<form name="redirectToBackFrominvoiceEwayBill" method="post">
	    <input type="hidden" name="startdate" value=""> 
	    <input  type="hidden" name="enddate" value="">
		<input type="hidden" name="getInvType" value=""> 
		<input type="hidden" name="onlyMonth" value="">
        <input type="hidden" name="onlyYear" value="">
        <input type="hidden" id="_csrf_token" name="_csrf_token" value="${_csrf_token}" />
</form>
